title: Tianyu Cui
logo: /assets/img/tianyucui.png
description: I'm a PhD Candidate at Probabilistic Machine Learning Group, Aalto University.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
